[package]
name = "archive-service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.24", features = ["rt-multi-thread", "macros", "time", "signal"] }
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
eyre = "0.6.12"
anyhow = "1.0"
rand = "0.8.5"

selendra-rust-client = { path = "../rust-client"}