[package]
name = "explorer-api"
version = "1.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.136", default-features = false, features = ["derive"] }
actix-web = "4.9.0"
dotenv = "0.15.0"
env_logger = "0.11.5"
log = "0.4.22"

selendra-db = { path = "../db"}