[package]
name = "scan-api"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
mongodb = { version = "2.1.0", default-features = false, features = ["sync"] }

operation = { path = "modules/operation"}
models = { path = "modules/models"}

[workspace]
members = [
    "modules/*",
]

