name: Selendra_Scan

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "main"

jobs:
  build:
   runs-on: ubuntu-latest

   strategy:
      matrix:
        node-version: [15.x, 16.x]
  
  steps:
  - uses: actions/checkout@v2
  - name: Setup and run build
    working-directory: ./crawler
    run: yarn
    run: yarn run build


